version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Проброс порта для взаимодействия с ASP.NET Core приложением

  frontend:
    build:
      context: C:\projects\ASP_NET_CORE\PLM_System\frontend  # Укажите путь к вашему фронтенд-приложению React
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Проброс порта для взаимодействия с React приложением
    depends_on:
      - backend  # Гарантирует, что бэкенд-сервис запускается перед фронтендом
